name: Update Adblock YAML

on:
  schedule:
    - cron: "0 2 * * *"  # 每天凌晨 2 点
  workflow_dispatch:     # 手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Merge adblock YAMLs and generate adblock_reject.yaml
        run: |
          python -c "
import requests, yaml

urls = [
  'https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml',
  'https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockmihomolite.yaml'
]

def download_yaml(url):
    r = requests.get(url)
    r.raise_for_status()
    return yaml.safe_load(r.text).get('payload', [])

rules = set()
for url in urls:
    rules.update(download_yaml(url))

with open('adblock_reject.yaml', 'w', encoding='utf-8') as f:
    yaml.dump({'payload': sorted(rules)}, f, allow_unicode=True)
print(f'Merged and saved {len(rules)} rules to adblock_reject.yaml')
          "

      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add adblock_reject.yaml
          git commit -m "Auto update adblock_reject.yaml"
          git push
